#!/bin/bash

BOLD=$(tput bold)
NORMAL=$(tput sgr0)

read -p "Please enter the key id you would like to use? " key_id
echo "The key id you want to decrypt with is: "
echo "${BOLD}$key_id${NORMAL}"

read -p "Please enter your encrypted value? " value
echo "The value you want to decrypt is: "
trimmed_value=$(echo "$value" | tr -d '\n')
echo -e "${BOLD}${trimmed_value}${NORMAL}"

read -p "Would you like to proceed with KeyID:[${BOLD}$key_id${NORMAL}] and the Value:[${BOLD}$trimmed_value${NORMAL}] ? (yes/no) " answer
printf "\n"
if [[ "$answer" == "yes" ]];then
    aws kms decrypt --ciphertext-blob fileb://<(echo $trimmed_value | base64 --decode) --output text --query Plaintext | base64 --decode
else
    echo "User elected not to proceed"
    exit 1
fi
