#!/bin/bash

BOLD=$(tput bold)
NORMAL=$(tput sgr0)

temp_file=$(mktemp $HOME/.secret.XXX)
trap '[ "$temp_file" ] && rm -f "$temp_file"' EXIT
sensitive_data=$(vi $temp_file >/dev/tty; cat $temp_file)
echo -e $sensitive_data | tr -d '\n' > $temp_file
echo "$BOLD${sensitive_data}$NORMAL"

read -p "Is this the correct value in which you want to encrypt? (yes/no) " value
if [[ "$value" != "yes" ]]; then
    echo "User elected not to proceed when prompted"
    exit 1
fi

read -p "Please enter the encryption key id you would like to use? " key_id
echo "The key id you want to encryt with is: "
echo "${BOLD}$key_id${NORMAL}"

read -p "Would you like to proceed encrypyting the value provided with KeyID:[${BOLD}$key_id${NORMAL}]? (yes/no) " answer
printf "\n"
if [[ "$answer" == "yes" ]];then
    aws kms encrypt --key-id $key_id --plaintext "fileb://$temp_file" --output text --query CiphertextBlob
else
    echo "User elected not to proceed"
    exit 1
fi
