#!/bin/bash

BOLD=$(tput bold)
NORMAL=$(tput sgr0)

read -p "Please enter the encryption key id you would like to use? " key_id
echo "The key id you want to encryt with is: "
echo "${BOLD}$key_id${NORMAL}"

read -p "Please enter your sensitive value to encrypt? " value
echo "The value you want to encryt is: "
trimmed_value=$(echo "$value" | tr -d '\n')
echo -e "${BOLD}${trimmed_value}${NORMAL}"

read -p "Would you like to proceed with KeyID:[${BOLD}$key_id${NORMAL}] and the Value:[${BOLD}$trimmed_value${NORMAL}] ? (yes/no) " answer
printf "\n"
if [[ "$answer" == "yes" ]];then
    aws kms encrypt --key-id $key_id --plaintext $trimmed_value --output text --query CiphertextBlob
else
    echo "User elected not to proceed"
    exit 1
fi
